---
- name: Firewall Configuration
  hosts: zfs_server
  become: yes
  vars_files:
    - vars/main.yml
  tasks:
    - name: Allow specified services
      firewalld:
        service: "{{ item }}"
        permanent: yes
        state: enabled
        immediate: yes
      loop: "{{ firewall_services }}"
