---
- name: Gather multipath devices
  hosts: zfs_server
  tasks:
    - name: Get list of multipath devices
      shell: "ls /dev/mapper/mpath* 2>/dev/null || echo ''"
      register: multipath_devices_output
      changed_when: false

    - name: Set multipath_devices fact
      set_fact:
        multipath_devices: "{{ multipath_devices_output.stdout.split() }}"
      when: multipath_devices_output.stdout != ''

    - name: Fail if no multipath devices found
      fail:
        msg: "No multipath devices found. Please check your configuration."
      when: multipath_devices_output.stdout == ''