---
- name: LUKS Encryption Setup
  hosts: servers
  become: yes
  vars_files:
    - vars/main.yml
  tasks:
    - name: Check if multipath device is already LUKS formatted
      command: cryptsetup isLuks {{ item }}
      register: is_luks
      failed_when: false
      changed_when: false
      loop: "{{ multipath_devices }}"

    - name: Format multipath devices with LUKS if not already formatted
      shell: echo "{{ luks_passphrase }}" | cryptsetup luksFormat --batch-mode - {{ item.item }}
      when: item.rc != 0  # rc != 0 means it’s not already LUKS formatted
      loop: "{{ is_luks.results }}"

    - name: Open LUKS-encrypted multipath devices
      command: cryptsetup luksOpen {{ item }} encrypted_{{ item | basename }}
      loop: "{{ multipath_devices }}"

    - name: Get UUIDs of multipath devices
      command: blkid -s UUID -o value {{ item }}
      register: disk_uuids
      loop: "{{ multipath_devices }}"

    - name: Add entries to /etc/crypttab
      lineinfile:
        path: /etc/crypttab
        line: "encrypted_{{ item.item | basename }} UUID={{ item.stdout }} none"
        state: present
      loop: "{{ disk_uuids.results }}"