---
- name: NFS-Ganesha Configuration
  hosts: zfs_server
  become: yes
  vars_files:
    - vars/main.yml
  tasks:
    - name: Configure NFS-Ganesha
      template:
        src: templates/ganesha.conf.j2
        dest: /etc/ganesha/ganesha.conf
        mode: '0644'

    - name: Enable and start NFS-Ganesha
      systemd:
        name: nfs-ganesha
        enabled: yes
        state: started
