---
- name: Samba Configuration
  hosts: zfs_server
  become: yes
  vars_files:
    - vars/main.yml
  tasks:
    - name: Configure Samba
      template:
        src: templates/smb.conf.j2
        dest: /etc/samba/smb.conf
        mode: '0644'

    - name: Add Samba users
      command: echo -e "password\npassword" | smbpasswd -a -s {{ item }}
      loop: "{{ samba_users }}"
      no_log: true

    - name: Enable and start Samba
      systemd:
        name: smb
        enabled: yes
        state: started
