---
- name: SELinux Configuration
  hosts: zfs_server
  become: yes
  tasks:
    - name: Set SELinux to permissive temporarily
      command: setenforce 0
      when: ansible_selinux is defined and ansible_selinux.status is defined and ansible_selinux.status == 'enabled' and ansible_selinux.mode != 'permissive'
      changed_when: true

    - name: Set SELinux to permissive persistently
      lineinfile:
        path: /etc/selinux/config
        regexp: '^SELINUX='
        line: 'SELINUX=permissive'
