---
- name: System Setup
  hosts: zfs_server
  become: yes

  tasks:
    - name: Update system
      yum:
        name: '*'
        state: latest

    - name: Install OpenZFS release package
      yum:
        name: oracle-openzfs-release-el8
        state: present

    - name: Install required packages
      yum:
        name: "{{ packages }}"
        state: present
