---
- name: ZFS Configuration
  hosts: servers
  become: yes
  vars_files:
    - vars/main.yml
  vars: 
    encrypted_devices: "{{ multipath_devices | map('basename') | map('regex_replace', '^', 'encrypted_') | list }}"

  tasks:
    - name: Validate disk count
      assert:
        that:
          - encrypted_devices | length >= total_disks_for_vdevs + spare_count
        fail_msg: "Insufficient disks: {{ encrypted_devices | length }} provided, but {{ total_disks_for_vdevs + spare_count }} required."

    - name: Create ZFS pool with encrypted multipath devices
      command: >
        zpool create -f -o ashift=12 {{ zpool_name }}
        {% for vdev in range(0, total_disks_for_vdevs, disks_per_vdev) %}
        raidz2 {{ encrypted_devices[vdev:vdev + disks_per_vdev] | map('regex_replace', '^', '/dev/mapper/') | join(' ') }}
        {% endfor %}
        spare {{ encrypted_devices[total_disks_for_vdevs:total_disks_for_vdevs + spare_count] | map('regex_replace', '^', '/dev/mapper/') | join(' ') }}
      args:
        creates: /{{ zpool_name }}

    - name: Create ZFS dataset
      zfs:
        name: "{{ zfs_dataset }}"
        state: present
        extra_zfs_properties:
          recordsize: 64K
          compression: lz4
          atime: off

